/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables.records;


import de.sharpadogge.twitchbot.jooq.tables.MusicSettings;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicSettingsRecord extends UpdatableRecordImpl<MusicSettingsRecord> implements Record3<Long, Long, String> {

    private static final long serialVersionUID = 862466893;

    /**
     * Setter for <code>twitchbot.music_settings.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitchbot.music_settings.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>twitchbot.music_settings.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitchbot.music_settings.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>twitchbot.music_settings.provider</code>.
     */
    public void setProvider(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitchbot.music_settings.provider</code>.
     */
    public String getProvider() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MusicSettings.MUSIC_SETTINGS.ID;
    }

    @Override
    public Field<Long> field2() {
        return MusicSettings.MUSIC_SETTINGS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return MusicSettings.MUSIC_SETTINGS.PROVIDER;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getProvider();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getProvider();
    }

    @Override
    public MusicSettingsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MusicSettingsRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public MusicSettingsRecord value3(String value) {
        setProvider(value);
        return this;
    }

    @Override
    public MusicSettingsRecord values(Long value1, Long value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MusicSettingsRecord
     */
    public MusicSettingsRecord() {
        super(MusicSettings.MUSIC_SETTINGS);
    }

    /**
     * Create a detached, initialised MusicSettingsRecord
     */
    public MusicSettingsRecord(Long id, Long userId, String provider) {
        super(MusicSettings.MUSIC_SETTINGS);

        set(0, id);
        set(1, userId);
        set(2, provider);
    }
}
