/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables.records;


import de.sharpadogge.twitchbot.jooq.tables.MusicYoutubeSettings;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicYoutubeSettingsRecord extends UpdatableRecordImpl<MusicYoutubeSettingsRecord> implements Record3<Long, Long, Integer> {

    private static final long serialVersionUID = 1391124071;

    /**
     * Setter for <code>twitchbot.music_youtube_settings.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitchbot.music_youtube_settings.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>twitchbot.music_youtube_settings.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitchbot.music_youtube_settings.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>twitchbot.music_youtube_settings.max_video_length</code>.
     */
    public void setMaxVideoLength(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitchbot.music_youtube_settings.max_video_length</code>.
     */
    public Integer getMaxVideoLength() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MusicYoutubeSettings.MUSIC_YOUTUBE_SETTINGS.ID;
    }

    @Override
    public Field<Long> field2() {
        return MusicYoutubeSettings.MUSIC_YOUTUBE_SETTINGS.USER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return MusicYoutubeSettings.MUSIC_YOUTUBE_SETTINGS.MAX_VIDEO_LENGTH;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Integer component3() {
        return getMaxVideoLength();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Integer value3() {
        return getMaxVideoLength();
    }

    @Override
    public MusicYoutubeSettingsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MusicYoutubeSettingsRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public MusicYoutubeSettingsRecord value3(Integer value) {
        setMaxVideoLength(value);
        return this;
    }

    @Override
    public MusicYoutubeSettingsRecord values(Long value1, Long value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MusicYoutubeSettingsRecord
     */
    public MusicYoutubeSettingsRecord() {
        super(MusicYoutubeSettings.MUSIC_YOUTUBE_SETTINGS);
    }

    /**
     * Create a detached, initialised MusicYoutubeSettingsRecord
     */
    public MusicYoutubeSettingsRecord(Long id, Long userId, Integer maxVideoLength) {
        super(MusicYoutubeSettings.MUSIC_YOUTUBE_SETTINGS);

        set(0, id);
        set(1, userId);
        set(2, maxVideoLength);
    }
}
