/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables.records;


import de.sharpadogge.twitchbot.jooq.tables.MusicYoutubePlaylist;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicYoutubePlaylistRecord extends UpdatableRecordImpl<MusicYoutubePlaylistRecord> implements Record6<Long, Long, String, Integer, String, String> {

    private static final long serialVersionUID = -3484006;

    /**
     * Setter for <code>twitchbot.music_youtube_playlist.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitchbot.music_youtube_playlist.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>twitchbot.music_youtube_playlist.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitchbot.music_youtube_playlist.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>twitchbot.music_youtube_playlist.video_id</code>.
     */
    public void setVideoId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitchbot.music_youtube_playlist.video_id</code>.
     */
    public String getVideoId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>twitchbot.music_youtube_playlist.video_duration_sec</code>.
     */
    public void setVideoDurationSec(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>twitchbot.music_youtube_playlist.video_duration_sec</code>.
     */
    public Integer getVideoDurationSec() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>twitchbot.music_youtube_playlist.video_title</code>.
     */
    public void setVideoTitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>twitchbot.music_youtube_playlist.video_title</code>.
     */
    public String getVideoTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>twitchbot.music_youtube_playlist.video_author</code>.
     */
    public void setVideoAuthor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>twitchbot.music_youtube_playlist.video_author</code>.
     */
    public String getVideoAuthor() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, Integer, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, Integer, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MusicYoutubePlaylist.MUSIC_YOUTUBE_PLAYLIST.ID;
    }

    @Override
    public Field<Long> field2() {
        return MusicYoutubePlaylist.MUSIC_YOUTUBE_PLAYLIST.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return MusicYoutubePlaylist.MUSIC_YOUTUBE_PLAYLIST.VIDEO_ID;
    }

    @Override
    public Field<Integer> field4() {
        return MusicYoutubePlaylist.MUSIC_YOUTUBE_PLAYLIST.VIDEO_DURATION_SEC;
    }

    @Override
    public Field<String> field5() {
        return MusicYoutubePlaylist.MUSIC_YOUTUBE_PLAYLIST.VIDEO_TITLE;
    }

    @Override
    public Field<String> field6() {
        return MusicYoutubePlaylist.MUSIC_YOUTUBE_PLAYLIST.VIDEO_AUTHOR;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getVideoId();
    }

    @Override
    public Integer component4() {
        return getVideoDurationSec();
    }

    @Override
    public String component5() {
        return getVideoTitle();
    }

    @Override
    public String component6() {
        return getVideoAuthor();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getVideoId();
    }

    @Override
    public Integer value4() {
        return getVideoDurationSec();
    }

    @Override
    public String value5() {
        return getVideoTitle();
    }

    @Override
    public String value6() {
        return getVideoAuthor();
    }

    @Override
    public MusicYoutubePlaylistRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MusicYoutubePlaylistRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public MusicYoutubePlaylistRecord value3(String value) {
        setVideoId(value);
        return this;
    }

    @Override
    public MusicYoutubePlaylistRecord value4(Integer value) {
        setVideoDurationSec(value);
        return this;
    }

    @Override
    public MusicYoutubePlaylistRecord value5(String value) {
        setVideoTitle(value);
        return this;
    }

    @Override
    public MusicYoutubePlaylistRecord value6(String value) {
        setVideoAuthor(value);
        return this;
    }

    @Override
    public MusicYoutubePlaylistRecord values(Long value1, Long value2, String value3, Integer value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MusicYoutubePlaylistRecord
     */
    public MusicYoutubePlaylistRecord() {
        super(MusicYoutubePlaylist.MUSIC_YOUTUBE_PLAYLIST);
    }

    /**
     * Create a detached, initialised MusicYoutubePlaylistRecord
     */
    public MusicYoutubePlaylistRecord(Long id, Long userId, String videoId, Integer videoDurationSec, String videoTitle, String videoAuthor) {
        super(MusicYoutubePlaylist.MUSIC_YOUTUBE_PLAYLIST);

        set(0, id);
        set(1, userId);
        set(2, videoId);
        set(3, videoDurationSec);
        set(4, videoTitle);
        set(5, videoAuthor);
    }
}
