/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables.records;


import de.sharpadogge.twitchbot.jooq.tables.TwitchCommandStatsDaily;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TwitchCommandStatsDailyRecord extends TableRecordImpl<TwitchCommandStatsDailyRecord> implements Record4<LocalDate, String, String, Long> {

    private static final long serialVersionUID = -1848498759;

    /**
     * Setter for <code>twitchbot.twitch_command_stats_daily.date</code>.
     */
    public void setDate(LocalDate value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitchbot.twitch_command_stats_daily.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(0);
    }

    /**
     * Setter for <code>twitchbot.twitch_command_stats_daily.channel</code>.
     */
    public void setChannel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitchbot.twitch_command_stats_daily.channel</code>.
     */
    public String getChannel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>twitchbot.twitch_command_stats_daily.cmd</code>.
     */
    public void setCmd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitchbot.twitch_command_stats_daily.cmd</code>.
     */
    public String getCmd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>twitchbot.twitch_command_stats_daily.call_count</code>.
     */
    public void setCallCount(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>twitchbot.twitch_command_stats_daily.call_count</code>.
     */
    public Long getCallCount() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<LocalDate, String, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<LocalDate, String, String, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<LocalDate> field1() {
        return TwitchCommandStatsDaily.TWITCH_COMMAND_STATS_DAILY.DATE;
    }

    @Override
    public Field<String> field2() {
        return TwitchCommandStatsDaily.TWITCH_COMMAND_STATS_DAILY.CHANNEL;
    }

    @Override
    public Field<String> field3() {
        return TwitchCommandStatsDaily.TWITCH_COMMAND_STATS_DAILY.CMD;
    }

    @Override
    public Field<Long> field4() {
        return TwitchCommandStatsDaily.TWITCH_COMMAND_STATS_DAILY.CALL_COUNT;
    }

    @Override
    public LocalDate component1() {
        return getDate();
    }

    @Override
    public String component2() {
        return getChannel();
    }

    @Override
    public String component3() {
        return getCmd();
    }

    @Override
    public Long component4() {
        return getCallCount();
    }

    @Override
    public LocalDate value1() {
        return getDate();
    }

    @Override
    public String value2() {
        return getChannel();
    }

    @Override
    public String value3() {
        return getCmd();
    }

    @Override
    public Long value4() {
        return getCallCount();
    }

    @Override
    public TwitchCommandStatsDailyRecord value1(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public TwitchCommandStatsDailyRecord value2(String value) {
        setChannel(value);
        return this;
    }

    @Override
    public TwitchCommandStatsDailyRecord value3(String value) {
        setCmd(value);
        return this;
    }

    @Override
    public TwitchCommandStatsDailyRecord value4(Long value) {
        setCallCount(value);
        return this;
    }

    @Override
    public TwitchCommandStatsDailyRecord values(LocalDate value1, String value2, String value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TwitchCommandStatsDailyRecord
     */
    public TwitchCommandStatsDailyRecord() {
        super(TwitchCommandStatsDaily.TWITCH_COMMAND_STATS_DAILY);
    }

    /**
     * Create a detached, initialised TwitchCommandStatsDailyRecord
     */
    public TwitchCommandStatsDailyRecord(LocalDate date, String channel, String cmd, Long callCount) {
        super(TwitchCommandStatsDaily.TWITCH_COMMAND_STATS_DAILY);

        set(0, date);
        set(1, channel);
        set(2, cmd);
        set(3, callCount);
    }
}
