/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables.records;


import de.sharpadogge.twitchbot.jooq.tables.UserCommand;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCommandRecord extends UpdatableRecordImpl<UserCommandRecord> implements Record10<Long, Long, String, Integer, Byte, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1831891076;

    /**
     * Setter for <code>twitchbot.user_command.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>twitchbot.user_command.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>twitchbot.user_command.cmd</code>.
     */
    public void setCmd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.cmd</code>.
     */
    public String getCmd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>twitchbot.user_command.argc</code>.
     */
    public void setArgc(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.argc</code>.
     */
    public Integer getArgc() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>twitchbot.user_command.enabled</code>.
     */
    public void setEnabled(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.enabled</code>.
     */
    public Byte getEnabled() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>twitchbot.user_command.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>twitchbot.user_command.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>twitchbot.user_command.global_delay</code>.
     */
    public void setGlobalDelay(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.global_delay</code>.
     */
    public Integer getGlobalDelay() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>twitchbot.user_command.user_delay</code>.
     */
    public void setUserDelay(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.user_delay</code>.
     */
    public Integer getUserDelay() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>twitchbot.user_command.cost</code>.
     */
    public void setCost(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>twitchbot.user_command.cost</code>.
     */
    public Integer getCost() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, String, Integer, Byte, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, String, Integer, Byte, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserCommand.USER_COMMAND.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserCommand.USER_COMMAND.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return UserCommand.USER_COMMAND.CMD;
    }

    @Override
    public Field<Integer> field4() {
        return UserCommand.USER_COMMAND.ARGC;
    }

    @Override
    public Field<Byte> field5() {
        return UserCommand.USER_COMMAND.ENABLED;
    }

    @Override
    public Field<String> field6() {
        return UserCommand.USER_COMMAND.NAME;
    }

    @Override
    public Field<String> field7() {
        return UserCommand.USER_COMMAND.DESCRIPTION;
    }

    @Override
    public Field<Integer> field8() {
        return UserCommand.USER_COMMAND.GLOBAL_DELAY;
    }

    @Override
    public Field<Integer> field9() {
        return UserCommand.USER_COMMAND.USER_DELAY;
    }

    @Override
    public Field<Integer> field10() {
        return UserCommand.USER_COMMAND.COST;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getCmd();
    }

    @Override
    public Integer component4() {
        return getArgc();
    }

    @Override
    public Byte component5() {
        return getEnabled();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getDescription();
    }

    @Override
    public Integer component8() {
        return getGlobalDelay();
    }

    @Override
    public Integer component9() {
        return getUserDelay();
    }

    @Override
    public Integer component10() {
        return getCost();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getCmd();
    }

    @Override
    public Integer value4() {
        return getArgc();
    }

    @Override
    public Byte value5() {
        return getEnabled();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getDescription();
    }

    @Override
    public Integer value8() {
        return getGlobalDelay();
    }

    @Override
    public Integer value9() {
        return getUserDelay();
    }

    @Override
    public Integer value10() {
        return getCost();
    }

    @Override
    public UserCommandRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserCommandRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserCommandRecord value3(String value) {
        setCmd(value);
        return this;
    }

    @Override
    public UserCommandRecord value4(Integer value) {
        setArgc(value);
        return this;
    }

    @Override
    public UserCommandRecord value5(Byte value) {
        setEnabled(value);
        return this;
    }

    @Override
    public UserCommandRecord value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserCommandRecord value7(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public UserCommandRecord value8(Integer value) {
        setGlobalDelay(value);
        return this;
    }

    @Override
    public UserCommandRecord value9(Integer value) {
        setUserDelay(value);
        return this;
    }

    @Override
    public UserCommandRecord value10(Integer value) {
        setCost(value);
        return this;
    }

    @Override
    public UserCommandRecord values(Long value1, Long value2, String value3, Integer value4, Byte value5, String value6, String value7, Integer value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserCommandRecord
     */
    public UserCommandRecord() {
        super(UserCommand.USER_COMMAND);
    }

    /**
     * Create a detached, initialised UserCommandRecord
     */
    public UserCommandRecord(Long id, Long userId, String cmd, Integer argc, Byte enabled, String name, String description, Integer globalDelay, Integer userDelay, Integer cost) {
        super(UserCommand.USER_COMMAND);

        set(0, id);
        set(1, userId);
        set(2, cmd);
        set(3, argc);
        set(4, enabled);
        set(5, name);
        set(6, description);
        set(7, globalDelay);
        set(8, userDelay);
        set(9, cost);
    }
}
