/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables;


import de.sharpadogge.twitchbot.jooq.Keys;
import de.sharpadogge.twitchbot.jooq.Twitchbot;
import de.sharpadogge.twitchbot.jooq.tables.records.MusicYoutubeSettingsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicYoutubeSettings extends TableImpl<MusicYoutubeSettingsRecord> {

    private static final long serialVersionUID = 861889961;

    /**
     * The reference instance of <code>twitchbot.music_youtube_settings</code>
     */
    public static final MusicYoutubeSettings MUSIC_YOUTUBE_SETTINGS = new MusicYoutubeSettings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MusicYoutubeSettingsRecord> getRecordType() {
        return MusicYoutubeSettingsRecord.class;
    }

    /**
     * The column <code>twitchbot.music_youtube_settings.id</code>.
     */
    public final TableField<MusicYoutubeSettingsRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>twitchbot.music_youtube_settings.user_id</code>.
     */
    public final TableField<MusicYoutubeSettingsRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitchbot.music_youtube_settings.max_video_length</code>.
     */
    public final TableField<MusicYoutubeSettingsRecord, Integer> MAX_VIDEO_LENGTH = createField(DSL.name("max_video_length"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("300", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>twitchbot.music_youtube_settings</code> table reference
     */
    public MusicYoutubeSettings() {
        this(DSL.name("music_youtube_settings"), null);
    }

    /**
     * Create an aliased <code>twitchbot.music_youtube_settings</code> table reference
     */
    public MusicYoutubeSettings(String alias) {
        this(DSL.name(alias), MUSIC_YOUTUBE_SETTINGS);
    }

    /**
     * Create an aliased <code>twitchbot.music_youtube_settings</code> table reference
     */
    public MusicYoutubeSettings(Name alias) {
        this(alias, MUSIC_YOUTUBE_SETTINGS);
    }

    private MusicYoutubeSettings(Name alias, Table<MusicYoutubeSettingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private MusicYoutubeSettings(Name alias, Table<MusicYoutubeSettingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> MusicYoutubeSettings(Table<O> child, ForeignKey<O, MusicYoutubeSettingsRecord> key) {
        super(child, key, MUSIC_YOUTUBE_SETTINGS);
    }

    @Override
    public Schema getSchema() {
        return Twitchbot.TWITCHBOT;
    }

    @Override
    public Identity<MusicYoutubeSettingsRecord, Long> getIdentity() {
        return Keys.IDENTITY_MUSIC_YOUTUBE_SETTINGS;
    }

    @Override
    public UniqueKey<MusicYoutubeSettingsRecord> getPrimaryKey() {
        return Keys.KEY_MUSIC_YOUTUBE_SETTINGS_PRIMARY;
    }

    @Override
    public List<UniqueKey<MusicYoutubeSettingsRecord>> getKeys() {
        return Arrays.<UniqueKey<MusicYoutubeSettingsRecord>>asList(Keys.KEY_MUSIC_YOUTUBE_SETTINGS_PRIMARY);
    }

    @Override
    public List<ForeignKey<MusicYoutubeSettingsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MusicYoutubeSettingsRecord, ?>>asList(Keys.FK_MUSIC_YOUTUBE_SETTINGS_USER_ID);
    }

    public Users users() {
        return new Users(this, Keys.FK_MUSIC_YOUTUBE_SETTINGS_USER_ID);
    }

    @Override
    public MusicYoutubeSettings as(String alias) {
        return new MusicYoutubeSettings(DSL.name(alias), this);
    }

    @Override
    public MusicYoutubeSettings as(Name alias) {
        return new MusicYoutubeSettings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MusicYoutubeSettings rename(String name) {
        return new MusicYoutubeSettings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MusicYoutubeSettings rename(Name name) {
        return new MusicYoutubeSettings(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
