/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables;


import de.sharpadogge.twitchbot.jooq.Keys;
import de.sharpadogge.twitchbot.jooq.Twitchbot;
import de.sharpadogge.twitchbot.jooq.tables.records.MusicYoutubeRequestsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MusicYoutubeRequests extends TableImpl<MusicYoutubeRequestsRecord> {

    private static final long serialVersionUID = 485130780;

    /**
     * The reference instance of <code>twitchbot.music_youtube_requests</code>
     */
    public static final MusicYoutubeRequests MUSIC_YOUTUBE_REQUESTS = new MusicYoutubeRequests();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MusicYoutubeRequestsRecord> getRecordType() {
        return MusicYoutubeRequestsRecord.class;
    }

    /**
     * The column <code>twitchbot.music_youtube_requests.id</code>.
     */
    public final TableField<MusicYoutubeRequestsRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>twitchbot.music_youtube_requests.user_id</code>.
     */
    public final TableField<MusicYoutubeRequestsRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitchbot.music_youtube_requests.video_id</code>.
     */
    public final TableField<MusicYoutubeRequestsRecord, String> VIDEO_ID = createField(DSL.name("video_id"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>twitchbot.music_youtube_requests.video_duration_sec</code>.
     */
    public final TableField<MusicYoutubeRequestsRecord, Integer> VIDEO_DURATION_SEC = createField(DSL.name("video_duration_sec"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>twitchbot.music_youtube_requests.video_title</code>.
     */
    public final TableField<MusicYoutubeRequestsRecord, String> VIDEO_TITLE = createField(DSL.name("video_title"), org.jooq.impl.SQLDataType.VARCHAR(512).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>twitchbot.music_youtube_requests.video_author</code>.
     */
    public final TableField<MusicYoutubeRequestsRecord, String> VIDEO_AUTHOR = createField(DSL.name("video_author"), org.jooq.impl.SQLDataType.VARCHAR(256).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>twitchbot.music_youtube_requests.requested_ts</code>.
     */
    public final TableField<MusicYoutubeRequestsRecord, LocalDateTime> REQUESTED_TS = createField(DSL.name("requested_ts"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>twitchbot.music_youtube_requests.requested_by</code>.
     */
    public final TableField<MusicYoutubeRequestsRecord, String> REQUESTED_BY = createField(DSL.name("requested_by"), org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>twitchbot.music_youtube_requests.finished</code>.
     */
    public final TableField<MusicYoutubeRequestsRecord, Byte> FINISHED = createField(DSL.name("finished"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>twitchbot.music_youtube_requests</code> table reference
     */
    public MusicYoutubeRequests() {
        this(DSL.name("music_youtube_requests"), null);
    }

    /**
     * Create an aliased <code>twitchbot.music_youtube_requests</code> table reference
     */
    public MusicYoutubeRequests(String alias) {
        this(DSL.name(alias), MUSIC_YOUTUBE_REQUESTS);
    }

    /**
     * Create an aliased <code>twitchbot.music_youtube_requests</code> table reference
     */
    public MusicYoutubeRequests(Name alias) {
        this(alias, MUSIC_YOUTUBE_REQUESTS);
    }

    private MusicYoutubeRequests(Name alias, Table<MusicYoutubeRequestsRecord> aliased) {
        this(alias, aliased, null);
    }

    private MusicYoutubeRequests(Name alias, Table<MusicYoutubeRequestsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> MusicYoutubeRequests(Table<O> child, ForeignKey<O, MusicYoutubeRequestsRecord> key) {
        super(child, key, MUSIC_YOUTUBE_REQUESTS);
    }

    @Override
    public Schema getSchema() {
        return Twitchbot.TWITCHBOT;
    }

    @Override
    public Identity<MusicYoutubeRequestsRecord, Long> getIdentity() {
        return Keys.IDENTITY_MUSIC_YOUTUBE_REQUESTS;
    }

    @Override
    public UniqueKey<MusicYoutubeRequestsRecord> getPrimaryKey() {
        return Keys.KEY_MUSIC_YOUTUBE_REQUESTS_PRIMARY;
    }

    @Override
    public List<UniqueKey<MusicYoutubeRequestsRecord>> getKeys() {
        return Arrays.<UniqueKey<MusicYoutubeRequestsRecord>>asList(Keys.KEY_MUSIC_YOUTUBE_REQUESTS_PRIMARY);
    }

    @Override
    public List<ForeignKey<MusicYoutubeRequestsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MusicYoutubeRequestsRecord, ?>>asList(Keys.FK_MUSIC_YOUTUBE_REQUESTS_USER_ID);
    }

    public Users users() {
        return new Users(this, Keys.FK_MUSIC_YOUTUBE_REQUESTS_USER_ID);
    }

    @Override
    public MusicYoutubeRequests as(String alias) {
        return new MusicYoutubeRequests(DSL.name(alias), this);
    }

    @Override
    public MusicYoutubeRequests as(Name alias) {
        return new MusicYoutubeRequests(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MusicYoutubeRequests rename(String name) {
        return new MusicYoutubeRequests(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MusicYoutubeRequests rename(Name name) {
        return new MusicYoutubeRequests(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, Integer, String, String, LocalDateTime, String, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
