/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables;


import de.sharpadogge.twitchbot.jooq.Twitchbot;
import de.sharpadogge.twitchbot.jooq.tables.records.TwitchCommandStatsDailyRecord;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TwitchCommandStatsDaily extends TableImpl<TwitchCommandStatsDailyRecord> {

    private static final long serialVersionUID = 694150070;

    /**
     * The reference instance of <code>twitchbot.twitch_command_stats_daily</code>
     */
    public static final TwitchCommandStatsDaily TWITCH_COMMAND_STATS_DAILY = new TwitchCommandStatsDaily();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TwitchCommandStatsDailyRecord> getRecordType() {
        return TwitchCommandStatsDailyRecord.class;
    }

    /**
     * The column <code>twitchbot.twitch_command_stats_daily.date</code>.
     */
    public final TableField<TwitchCommandStatsDailyRecord, LocalDate> DATE = createField(DSL.name("date"), org.jooq.impl.SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>twitchbot.twitch_command_stats_daily.channel</code>.
     */
    public final TableField<TwitchCommandStatsDailyRecord, String> CHANNEL = createField(DSL.name("channel"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>twitchbot.twitch_command_stats_daily.cmd</code>.
     */
    public final TableField<TwitchCommandStatsDailyRecord, String> CMD = createField(DSL.name("cmd"), org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>twitchbot.twitch_command_stats_daily.call_count</code>.
     */
    public final TableField<TwitchCommandStatsDailyRecord, Long> CALL_COUNT = createField(DSL.name("call_count"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>twitchbot.twitch_command_stats_daily</code> table reference
     */
    public TwitchCommandStatsDaily() {
        this(DSL.name("twitch_command_stats_daily"), null);
    }

    /**
     * Create an aliased <code>twitchbot.twitch_command_stats_daily</code> table reference
     */
    public TwitchCommandStatsDaily(String alias) {
        this(DSL.name(alias), TWITCH_COMMAND_STATS_DAILY);
    }

    /**
     * Create an aliased <code>twitchbot.twitch_command_stats_daily</code> table reference
     */
    public TwitchCommandStatsDaily(Name alias) {
        this(alias, TWITCH_COMMAND_STATS_DAILY);
    }

    private TwitchCommandStatsDaily(Name alias, Table<TwitchCommandStatsDailyRecord> aliased) {
        this(alias, aliased, null);
    }

    private TwitchCommandStatsDaily(Name alias, Table<TwitchCommandStatsDailyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TwitchCommandStatsDaily(Table<O> child, ForeignKey<O, TwitchCommandStatsDailyRecord> key) {
        super(child, key, TWITCH_COMMAND_STATS_DAILY);
    }

    @Override
    public Schema getSchema() {
        return Twitchbot.TWITCHBOT;
    }

    @Override
    public TwitchCommandStatsDaily as(String alias) {
        return new TwitchCommandStatsDaily(DSL.name(alias), this);
    }

    @Override
    public TwitchCommandStatsDaily as(Name alias) {
        return new TwitchCommandStatsDaily(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TwitchCommandStatsDaily rename(String name) {
        return new TwitchCommandStatsDaily(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TwitchCommandStatsDaily rename(Name name) {
        return new TwitchCommandStatsDaily(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<LocalDate, String, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
