/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables;


import de.sharpadogge.twitchbot.jooq.Keys;
import de.sharpadogge.twitchbot.jooq.Twitchbot;
import de.sharpadogge.twitchbot.jooq.tables.records.UserCommandActionRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCommandAction extends TableImpl<UserCommandActionRecord> {

    private static final long serialVersionUID = -2127404576;

    /**
     * The reference instance of <code>twitchbot.user_command_action</code>
     */
    public static final UserCommandAction USER_COMMAND_ACTION = new UserCommandAction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserCommandActionRecord> getRecordType() {
        return UserCommandActionRecord.class;
    }

    /**
     * The column <code>twitchbot.user_command_action.user_id</code>.
     */
    public final TableField<UserCommandActionRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitchbot.user_command_action.command_id</code>.
     */
    public final TableField<UserCommandActionRecord, Long> COMMAND_ID = createField(DSL.name("command_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitchbot.user_command_action.idx</code>.
     */
    public final TableField<UserCommandActionRecord, Integer> IDX = createField(DSL.name("idx"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>twitchbot.user_command_action.action</code>.
     */
    public final TableField<UserCommandActionRecord, String> ACTION = createField(DSL.name("action"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * Create a <code>twitchbot.user_command_action</code> table reference
     */
    public UserCommandAction() {
        this(DSL.name("user_command_action"), null);
    }

    /**
     * Create an aliased <code>twitchbot.user_command_action</code> table reference
     */
    public UserCommandAction(String alias) {
        this(DSL.name(alias), USER_COMMAND_ACTION);
    }

    /**
     * Create an aliased <code>twitchbot.user_command_action</code> table reference
     */
    public UserCommandAction(Name alias) {
        this(alias, USER_COMMAND_ACTION);
    }

    private UserCommandAction(Name alias, Table<UserCommandActionRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserCommandAction(Name alias, Table<UserCommandActionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> UserCommandAction(Table<O> child, ForeignKey<O, UserCommandActionRecord> key) {
        super(child, key, USER_COMMAND_ACTION);
    }

    @Override
    public Schema getSchema() {
        return Twitchbot.TWITCHBOT;
    }

    @Override
    public UniqueKey<UserCommandActionRecord> getPrimaryKey() {
        return Keys.KEY_USER_COMMAND_ACTION_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserCommandActionRecord>> getKeys() {
        return Arrays.<UniqueKey<UserCommandActionRecord>>asList(Keys.KEY_USER_COMMAND_ACTION_PRIMARY);
    }

    @Override
    public List<ForeignKey<UserCommandActionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserCommandActionRecord, ?>>asList(Keys.FK_USER_COMMAND_ACTION_USER_ID, Keys.FK_USER_COMMAND_ACTION_COMMAND_ID);
    }

    public Users users() {
        return new Users(this, Keys.FK_USER_COMMAND_ACTION_USER_ID);
    }

    public UserCommand userCommand() {
        return new UserCommand(this, Keys.FK_USER_COMMAND_ACTION_COMMAND_ID);
    }

    @Override
    public UserCommandAction as(String alias) {
        return new UserCommandAction(DSL.name(alias), this);
    }

    @Override
    public UserCommandAction as(Name alias) {
        return new UserCommandAction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCommandAction rename(String name) {
        return new UserCommandAction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCommandAction rename(Name name) {
        return new UserCommandAction(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
