/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables;


import de.sharpadogge.twitchbot.jooq.Keys;
import de.sharpadogge.twitchbot.jooq.Twitchbot;
import de.sharpadogge.twitchbot.jooq.tables.records.UserCommandAliasRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCommandAlias extends TableImpl<UserCommandAliasRecord> {

    private static final long serialVersionUID = -480422119;

    /**
     * The reference instance of <code>twitchbot.user_command_alias</code>
     */
    public static final UserCommandAlias USER_COMMAND_ALIAS = new UserCommandAlias();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserCommandAliasRecord> getRecordType() {
        return UserCommandAliasRecord.class;
    }

    /**
     * The column <code>twitchbot.user_command_alias.user_id</code>.
     */
    public final TableField<UserCommandAliasRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitchbot.user_command_alias.command_id</code>.
     */
    public final TableField<UserCommandAliasRecord, Long> COMMAND_ID = createField(DSL.name("command_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitchbot.user_command_alias.alias</code>.
     */
    public final TableField<UserCommandAliasRecord, String> ALIAS = createField(DSL.name("alias"), org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * Create a <code>twitchbot.user_command_alias</code> table reference
     */
    public UserCommandAlias() {
        this(DSL.name("user_command_alias"), null);
    }

    /**
     * Create an aliased <code>twitchbot.user_command_alias</code> table reference
     */
    public UserCommandAlias(String alias) {
        this(DSL.name(alias), USER_COMMAND_ALIAS);
    }

    /**
     * Create an aliased <code>twitchbot.user_command_alias</code> table reference
     */
    public UserCommandAlias(Name alias) {
        this(alias, USER_COMMAND_ALIAS);
    }

    private UserCommandAlias(Name alias, Table<UserCommandAliasRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserCommandAlias(Name alias, Table<UserCommandAliasRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> UserCommandAlias(Table<O> child, ForeignKey<O, UserCommandAliasRecord> key) {
        super(child, key, USER_COMMAND_ALIAS);
    }

    @Override
    public Schema getSchema() {
        return Twitchbot.TWITCHBOT;
    }

    @Override
    public UniqueKey<UserCommandAliasRecord> getPrimaryKey() {
        return Keys.KEY_USER_COMMAND_ALIAS_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserCommandAliasRecord>> getKeys() {
        return Arrays.<UniqueKey<UserCommandAliasRecord>>asList(Keys.KEY_USER_COMMAND_ALIAS_PRIMARY);
    }

    @Override
    public List<ForeignKey<UserCommandAliasRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserCommandAliasRecord, ?>>asList(Keys.FK_USER_COMMAND_ALIAS_USER_ID, Keys.FK_USER_COMMAND_ALIAS_COMMAND_ID);
    }

    public Users users() {
        return new Users(this, Keys.FK_USER_COMMAND_ALIAS_USER_ID);
    }

    public UserCommand userCommand() {
        return new UserCommand(this, Keys.FK_USER_COMMAND_ALIAS_COMMAND_ID);
    }

    @Override
    public UserCommandAlias as(String alias) {
        return new UserCommandAlias(DSL.name(alias), this);
    }

    @Override
    public UserCommandAlias as(Name alias) {
        return new UserCommandAlias(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCommandAlias rename(String name) {
        return new UserCommandAlias(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCommandAlias rename(Name name) {
        return new UserCommandAlias(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
