/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables;


import de.sharpadogge.twitchbot.jooq.Keys;
import de.sharpadogge.twitchbot.jooq.Twitchbot;
import de.sharpadogge.twitchbot.jooq.tables.records.UserUrlWhitelistRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserUrlWhitelist extends TableImpl<UserUrlWhitelistRecord> {

    private static final long serialVersionUID = 1782894456;

    /**
     * The reference instance of <code>twitchbot.user_url_whitelist</code>
     */
    public static final UserUrlWhitelist USER_URL_WHITELIST = new UserUrlWhitelist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserUrlWhitelistRecord> getRecordType() {
        return UserUrlWhitelistRecord.class;
    }

    /**
     * The column <code>twitchbot.user_url_whitelist.user_id</code>.
     */
    public final TableField<UserUrlWhitelistRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitchbot.user_url_whitelist.url</code>.
     */
    public final TableField<UserUrlWhitelistRecord, String> URL = createField(DSL.name("url"), org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * Create a <code>twitchbot.user_url_whitelist</code> table reference
     */
    public UserUrlWhitelist() {
        this(DSL.name("user_url_whitelist"), null);
    }

    /**
     * Create an aliased <code>twitchbot.user_url_whitelist</code> table reference
     */
    public UserUrlWhitelist(String alias) {
        this(DSL.name(alias), USER_URL_WHITELIST);
    }

    /**
     * Create an aliased <code>twitchbot.user_url_whitelist</code> table reference
     */
    public UserUrlWhitelist(Name alias) {
        this(alias, USER_URL_WHITELIST);
    }

    private UserUrlWhitelist(Name alias, Table<UserUrlWhitelistRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserUrlWhitelist(Name alias, Table<UserUrlWhitelistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> UserUrlWhitelist(Table<O> child, ForeignKey<O, UserUrlWhitelistRecord> key) {
        super(child, key, USER_URL_WHITELIST);
    }

    @Override
    public Schema getSchema() {
        return Twitchbot.TWITCHBOT;
    }

    @Override
    public UniqueKey<UserUrlWhitelistRecord> getPrimaryKey() {
        return Keys.KEY_USER_URL_WHITELIST_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserUrlWhitelistRecord>> getKeys() {
        return Arrays.<UniqueKey<UserUrlWhitelistRecord>>asList(Keys.KEY_USER_URL_WHITELIST_PRIMARY);
    }

    @Override
    public List<ForeignKey<UserUrlWhitelistRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserUrlWhitelistRecord, ?>>asList(Keys.FK_URL_WHITELIST_USER_ID);
    }

    public Users users() {
        return new Users(this, Keys.FK_URL_WHITELIST_USER_ID);
    }

    @Override
    public UserUrlWhitelist as(String alias) {
        return new UserUrlWhitelist(DSL.name(alias), this);
    }

    @Override
    public UserUrlWhitelist as(Name alias) {
        return new UserUrlWhitelist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserUrlWhitelist rename(String name) {
        return new UserUrlWhitelist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserUrlWhitelist rename(Name name) {
        return new UserUrlWhitelist(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
