/*
 * This file is generated by jOOQ.
 */
package de.sharpadogge.twitchbot.jooq.tables;


import de.sharpadogge.twitchbot.jooq.Keys;
import de.sharpadogge.twitchbot.jooq.Twitchbot;
import de.sharpadogge.twitchbot.jooq.tables.records.UserCommandPermissionRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCommandPermission extends TableImpl<UserCommandPermissionRecord> {

    private static final long serialVersionUID = -1827658478;

    /**
     * The reference instance of <code>twitchbot.user_command_permission</code>
     */
    public static final UserCommandPermission USER_COMMAND_PERMISSION = new UserCommandPermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserCommandPermissionRecord> getRecordType() {
        return UserCommandPermissionRecord.class;
    }

    /**
     * The column <code>twitchbot.user_command_permission.user_id</code>.
     */
    public final TableField<UserCommandPermissionRecord, Long> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitchbot.user_command_permission.command_id</code>.
     */
    public final TableField<UserCommandPermissionRecord, Long> COMMAND_ID = createField(DSL.name("command_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>twitchbot.user_command_permission.permission</code>.
     */
    public final TableField<UserCommandPermissionRecord, String> PERMISSION = createField(DSL.name("permission"), org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * Create a <code>twitchbot.user_command_permission</code> table reference
     */
    public UserCommandPermission() {
        this(DSL.name("user_command_permission"), null);
    }

    /**
     * Create an aliased <code>twitchbot.user_command_permission</code> table reference
     */
    public UserCommandPermission(String alias) {
        this(DSL.name(alias), USER_COMMAND_PERMISSION);
    }

    /**
     * Create an aliased <code>twitchbot.user_command_permission</code> table reference
     */
    public UserCommandPermission(Name alias) {
        this(alias, USER_COMMAND_PERMISSION);
    }

    private UserCommandPermission(Name alias, Table<UserCommandPermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserCommandPermission(Name alias, Table<UserCommandPermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> UserCommandPermission(Table<O> child, ForeignKey<O, UserCommandPermissionRecord> key) {
        super(child, key, USER_COMMAND_PERMISSION);
    }

    @Override
    public Schema getSchema() {
        return Twitchbot.TWITCHBOT;
    }

    @Override
    public UniqueKey<UserCommandPermissionRecord> getPrimaryKey() {
        return Keys.KEY_USER_COMMAND_PERMISSION_PRIMARY;
    }

    @Override
    public List<UniqueKey<UserCommandPermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<UserCommandPermissionRecord>>asList(Keys.KEY_USER_COMMAND_PERMISSION_PRIMARY);
    }

    @Override
    public List<ForeignKey<UserCommandPermissionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<UserCommandPermissionRecord, ?>>asList(Keys.FK_USER_COMMAND_PERMISSION_USER_ID, Keys.FK_USER_COMMAND_PERMISSION_COMMAND_ID);
    }

    public Users users() {
        return new Users(this, Keys.FK_USER_COMMAND_PERMISSION_USER_ID);
    }

    public UserCommand userCommand() {
        return new UserCommand(this, Keys.FK_USER_COMMAND_PERMISSION_COMMAND_ID);
    }

    @Override
    public UserCommandPermission as(String alias) {
        return new UserCommandPermission(DSL.name(alias), this);
    }

    @Override
    public UserCommandPermission as(Name alias) {
        return new UserCommandPermission(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCommandPermission rename(String name) {
        return new UserCommandPermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserCommandPermission rename(Name name) {
        return new UserCommandPermission(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
